[package]
name = "market-hawk-project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curl = "*"
serde_json = "*"
serde = "*"
chrono = "*"
statrs = "*"
anyhow = "*"
